-- 1-9 Basic ---- Basic -- -- Basic -- -- Basic -- -- Basic -- -- Basic -- -- Basic -- -- Basic -- -- Basic -- -- Basic -- -- Basic -- -- Basic -- -- Basic -- -- Basic -- -- Basic -- -- Basic -- -- Basic -- -- Basic -- -- Basic -- -- Basic --
INSERT INTO public."Category" (ecosystem, key, name, "tagline", "desc", priority,"isSuperCategory", "superCatagory", "extJson", "createBy", "createDt", "modifyBy", "modifyDt") VALUES ('TON', 'wallet','Wallet', 'Store and manage your crypto assets.',null, 1, false,null, null, null, '2024-09-10 02:46:19.181', null, null);
INSERT INTO public."Category" (ecosystem, key, name, "tagline", "desc", priority,"isSuperCategory", "superCatagory", "extJson", "createBy", "createDt", "modifyBy", "modifyDt") VALUES ('TON', 'explorer','Explorer', 'Browse transactions on blockchain.',null, 2, false,null, null, null, '2024-09-10 02:46:19.181', null, null);
INSERT INTO public."Category" (ecosystem, key, name, "tagline", "desc", priority,"isSuperCategory", "superCatagory", "extJson", "createBy", "createDt", "modifyBy", "modifyDt") VALUES ('TON', 'community','Community', 'Connect and communicate within the TON community.',null, 3, false,null, null, null, '2024-09-10 02:46:19.181', null, null);
INSERT INTO public."Category" (ecosystem, key, name, "tagline", "desc", priority,"isSuperCategory", "superCatagory", "extJson", "createBy", "createDt", "modifyBy", "modifyDt") VALUES ('TON', 'game','Game', 'Immerse yourself in blockchain-based games on TON.',null, 4, false,null, null, null, '2024-09-10 02:46:19.181', null, null);
INSERT INTO public."Category" (ecosystem, key, name, "tagline", "desc", priority,"isSuperCategory", "superCatagory", "extJson", "createBy", "createDt", "modifyBy", "modifyDt") VALUES ('TON', 'NFT','NFT', 'Explore NFT Collections of TON Blockchain.',null, 5, false,null, null, null, '2024-09-10 02:46:19.181', null, null);
INSERT INTO public."Category" (ecosystem, key, name, "tagline", "desc", priority,"isSuperCategory", "superCatagory", "extJson", "createBy", "createDt", "modifyBy", "modifyDt") VALUES ('TON', 'launchpad','Launchpad', 'The gateway to exciting new projects.',null, 6, false,null, null, null, '2024-09-10 02:46:19.181', null, null);


-- 10 DeFi -- -- DeFi -- -- DeFi -- -- DeFi -- -- DeFi -- -- DeFi -- -- DeFi -- -- DeFi -- -- DeFi -- -- DeFi -- -- DeFi -- -- DeFi -- -- DeFi -- -- DeFi -- -- DeFi -- -- DeFi -- -- DeFi -- -- DeFi -- -- DeFi -- -- DeFi -- -- DeFi -- -- DeFi -- -- DeFi -- -- DeFi -- -- DeFi -- -- DeFi --
INSERT INTO public."Category" (ecosystem, key, name, "tagline", "desc", priority,"isSuperCategory", "superCatagory", "extJson", "createBy", "createDt", "modifyBy", "modifyDt") VALUES ('TON', 'DeFi','DeFi', 'Maximize your Toncoin with staking apps.',null, 10, true,null, null, null, '2024-09-10 02:46:19.181', null, null);
INSERT INTO public."Category" (ecosystem, key, name, "tagline", "desc", priority,"isSuperCategory", "superCatagory", "extJson", "createBy", "createDt", "modifyBy", "modifyDt") VALUES ('TON', 'DEX','DEX', 'Trade cryptocurrencies directly on TON Blockchain.',null, 11, false,'DeFi', null, null, '2024-09-10 02:46:19.181', null, null);
INSERT INTO public."Category" (ecosystem, key, name, "tagline", "desc", priority,"isSuperCategory", "superCatagory", "extJson", "createBy", "createDt", "modifyBy", "modifyDt") VALUES ('TON', 'staking','Staking', 'Maximize your Toncoin with staking apps.',null, 12, false,'DeFi', null, null, '2024-09-10 02:46:19.181', null, null);
INSERT INTO public."Category" (ecosystem, key, name, "tagline", "desc", priority,"isSuperCategory", "superCatagory", "extJson", "createBy", "createDt", "modifyBy", "modifyDt") VALUES ('TON', 'stablecoin','Stablecoin', 'A cryptocurrency with a stable value.',null, 13, false,'DeFi', null, null, '2024-09-10 02:46:19.181', null, null);
INSERT INTO public."Category" (ecosystem, key, name, "tagline", "desc", priority,"isSuperCategory", "superCatagory", "extJson", "createBy", "createDt", "modifyBy", "modifyDt") VALUES ('TON', 'lending','Lending', 'Borrow or lend crypto assets for interest.',null, 14, false,'DeFi', null, null, '2024-09-10 02:46:19.181', null, null);

-- 20 financial & cross border TX ---- financial & cross border TX ---- financial & cross border TX ---- financial & cross border TX ---- financial & cross border TX ---- financial & cross border TX ---- financial & cross border TX ---- financial & cross border TX ---- financial & cross border TX ---- financial & cross border TX --
INSERT INTO public."Category" (ecosystem, key, name, "tagline", "desc", priority,"isSuperCategory", "superCatagory", "extJson", "createBy", "createDt", "modifyBy", "modifyDt") VALUES ('TON', 'CEX','CEX', 'Buy and sell Toncoin on CEXes.',null, 21, false,null, null, null, '2024-09-10 02:46:19.181', null, null);
INSERT INTO public."Category" (ecosystem, key, name, "tagline", "desc", priority,"isSuperCategory", "superCatagory", "extJson", "createBy", "createDt", "modifyBy", "modifyDt") VALUES ('TON', 'onramp','On-Ramp', 'Maximize your Toncoin with staking apps.',null, 22, false,null, null, null, '2024-09-10 02:46:19.181', null, null);
INSERT INTO public."Category" (ecosystem, key, name, "tagline", "desc", priority,"isSuperCategory", "superCatagory", "extJson", "createBy", "createDt", "modifyBy", "modifyDt") VALUES ('TON', 'bridge','Bridge', 'Transfer crypto assets between chains.',null, 23, false,null, null, null, '2024-09-10 02:46:19.181', null, null);

-- 30 Application -- -- Application -- -- Application -- -- Application -- -- Application -- -- Application -- -- Application -- -- Application -- -- Application -- -- Application -- -- Application -- -- Application -- -- Application -- -- Application --
INSERT INTO public."Category" (ecosystem, key, name, "tagline", "desc", priority,"isSuperCategory", "superCatagory", "extJson", "createBy", "createDt", "modifyBy", "modifyDt") VALUES ('TON', 'application','Application', 'Application scenarios for mainstream users.',null, 30, false,null, null, null, '2024-09-10 02:46:19.181', null, null);
INSERT INTO public."Category" (ecosystem, key, name, "tagline", "desc", priority,"isSuperCategory", "superCatagory", "extJson", "createBy", "createDt", "modifyBy", "modifyDt") VALUES ('TON', 'social','Social', 'Experience social networks powered by TON Blockchain.',null, 31, false,null, null, null, '2024-09-10 02:46:19.181', null, null);
INSERT INTO public."Category" (ecosystem, key, name, "tagline", "desc", priority,"isSuperCategory", "superCatagory", "extJson", "createBy", "createDt", "modifyBy", "modifyDt") VALUES ('TON', 'gambling','Gambling', 'Discover gambling apps on TON. ',null, 32, false,null, null, null, '2024-09-10 02:46:19.181', null, null);


-- 40 Infrastructure ---- Infrastructure ---- Infrastructure ---- Infrastructure ---- Infrastructure --
INSERT INTO public."Category" (ecosystem, key, name, "tagline", "desc", priority,"isSuperCategory", "superCatagory", "extJson", "createBy", "createDt", "modifyBy", "modifyDt") VALUES ('TON', 'infrastructure','Infrastructure', 'Dev Tools, RPC Node, Data Service and so on',null, 40, true,null, null, null, '2024-09-10 02:46:19.181', null, null);


-- 50 Utility -- -- Utility -- -- Utility -- -- Utility -- -- Utility -- -- Utility -- -- Utility -- -- Utility -- -- Utility -- -- Utility -- -- Utility -- -- Utility -- -- Utility -- -- Utility -- -- Utility -- -- Utility -- -- Utility -- -- Utility -- -- Utility --
INSERT INTO public."Category" (ecosystem, key, name, "tagline", "desc", priority,"isSuperCategory", "superCatagory", "extJson", "createBy", "createDt", "modifyBy", "modifyDt") VALUES ('TON', 'utility','Utility', 'Useful tools or services',null, 50, true,null, null, null, '2024-09-10 02:46:19.181', null, null);



-- 90 miscellaneous ---- miscellaneous ---- miscellaneous ---- miscellaneous ---- miscellaneous ---- miscellaneous ---- miscellaneous ---- miscellaneous ---- miscellaneous ---- miscellaneous ---- miscellaneous ---- miscellaneous ---- miscellaneous ---- miscellaneous ---- miscellaneous ---- miscellaneous --
INSERT INTO public."Category" (ecosystem, key, name, "tagline", "desc", priority,"isSuperCategory", "superCatagory", "extJson", "createBy", "createDt", "modifyBy", "modifyDt") VALUES ('TON', 'DAO','DAO', 'Decentralized Autonomous Organization',null, 91, false,'Infrastructure', null, null, '2024-09-10 02:46:19.181', null, null);
INSERT INTO public."Category" (ecosystem, key, name, "tagline", "desc", priority,"isSuperCategory", "superCatagory", "extJson", "createBy", "createDt", "modifyBy", "modifyDt") VALUES ('TON', 'RWA','RWA', 'Real World Assets tokenized on blockchain',null, 92, false,'Infrastructure', null, null, '2024-09-10 02:46:19.181', null, null);

