insert into public."Project" ("ownerTgId", "name", tagline, "langCodes", website, twitter, "tgChannel", "tgChat",
                              "tgBot", "iconImg")
values (5499157826,
        'Tonkeeper',
        'A mobile wallet in your pocket',
        'en ru',
        'https://tonkeeper.com',
        null,
        'https://t.me/tonkeeper',
        null,
        null,
        'https://ton.app/media/5c99e268-7c6e-4712-bc9c-1aa244ca0166.jpg');
insert into public."Project" ("ownerTgId", "name", tagline, "langCodes", website, twitter, "tgChannel", "tgChat",
                              "tgBot", "iconImg")
values (5499157826,
        'Wallet',
        'Easiest way to get crypto in Telegram',
        'en ru',
        'https://t.me/wallet',
        null,
        'https://t.me/wallet_news',
        'https://t.me/wallet_news_en_chat',
        'https://t.me/wallet',
        'https://ton.app/media/f0a3e507-9500-41af-8d91-9188f72c50c0.jpg');
insert into public."Project" ("ownerTgId", "name", tagline, "langCodes", website, twitter, "tgChannel", "tgChat",
                              "tgBot", "iconImg")
values (5499157826,
        'MyTonWallet',
        'The most feature-rich and security-oriented wallet for TON',
        null,
        'https://mytonwallet.io',
        null,
        'https://t.me/MyTonWalletEn',
        'https://t.me/mytonwallet_group',
        null,
        'https://ton.app/media/d2db8af3-b5fa-458b-a721-7142b2c82112.png');
insert into public."Project" ("ownerTgId", "name", tagline, "langCodes", website, twitter, "tgChannel", "tgChat",
                              "tgBot", "iconImg")
values (5499157826,
        'Tonhub',
        'Crypto wallet for TON',
        null,
        'https://tonhub.com/dl',
        'https://twitter.com/whalescorp',
        'https://t.me/tonhub',
        null,
        null,
        'https://ton.app/media/89f2c6f5-6b18-4f4b-9b57-1912397345dc.png');
insert into public."Project" ("ownerTgId", "name", tagline, "langCodes", website, twitter, "tgChannel", "tgChat",
                              "tgBot", "iconImg")
values (5499157826,
        'Crypto Bot',
        'Simple. Reliable. Powerful',
        'en ru',
        'https://t.me/cryptobot',
        null,
        'https://t.me/CryptoBotEN',
        'https://t.me/CryptoBotEnglish',
        'https://t.me/cryptobot',
        'https://ton.app/media/f3745724-e66c-4aaa-ad11-90249a6ed78e.jpg');
insert into public."Project" ("ownerTgId", "name", tagline, "langCodes", website, twitter, "tgChannel", "tgChat",
                              "tgBot", "iconImg")
values (5499157826,
        'Trust Wallet',
        'The most trusted & secure crypto wallet',
        null,
        'https://trustwallet.com',
        null,
        null,
        null,
        null,
        'https://ton.app/media/a59c4405-1086-456e-8100-9dc1e5763ff4.jpg');
insert into public."Project" ("ownerTgId", "name", tagline, "langCodes", website, twitter, "tgChannel", "tgChat",
                              "tgBot", "iconImg")
values (5499157826,
        'OpenMask',
        'A TON Wallet in your Browser',
        null,
        'https://www.openmask.app/',
        null,
        null,
        null,
        null,
        'https://ton.app/media/08d84727-15d1-4058-9b74-9474e4488f70.jpg');
insert into public."Project" ("ownerTgId", "name", tagline, "langCodes", website, twitter, "tgChannel", "tgChat",
                              "tgBot", "iconImg")
values (5499157826,
        'DeWallet',
        'Delab Wallet Ton',
        'en',
        'https://chrome.google.com/webstore/detail/dewallet/pnccjgokhbnggghddhahcnaopgeipafg',
        null,
        'https://t.me/delab',
        null,
        'https://t.me/delabtonbot',
        'https://ton.app/media/dc48dd59-34ad-42a4-818f-9ec80232c735.jpg');
insert into public."Project" ("ownerTgId", "name", tagline, "langCodes", website, twitter, "tgChannel", "tgChat",
                              "tgBot", "iconImg")
values (5499157826,
        'SafePal',
        'cryptocurrency wallet application is a secure, decentralized, easy-to-use ',
        null,
        'https://www.safepal.com',
        null,
        null,
        null,
        null,
        'https://ton.app/media/a0fa6ebb-1cca-487b-8277-ef6378f66ba5.jpg');
insert into public."Project" ("ownerTgId", "name", tagline, "langCodes", website, twitter, "tgChannel", "tgChat",
                              "tgBot", "iconImg")
values (5499157826,
        'Swapster',
        'Multicurrency crypto wallet in Telegram',
        'en ru',
        'https://t.me/swapsterbot?start=aqy',
        'https://twitter.com/swapsterteam',
        'https://t.me/swpstr',
        'https://t.me/SwapsterSupport',
        'https://t.me/swapsterbot?start=AQY',
        'https://ton.app/media/f7ffc7ac-1eb9-436c-a298-bb44acf2cff0.jpg');
insert into public."Project" ("ownerTgId", "name", tagline, "langCodes", website, twitter, "tgChannel", "tgChat",
                              "tgBot", "iconImg")
values (5499157826,
        'xRocket',
        'Cryptocurrency telegram wallet with built-in CEX',
        'en ru',
        'http://t.me/xrocket',
        null,
        null,
        null,
        'https://t.me/xrocket',
        'https://ton.app/media/3f30dde6-870b-4d0b-a2d1-201666e01a41.png');
insert into public."Project" ("ownerTgId", "name", tagline, "langCodes", website, twitter, "tgChannel", "tgChat",
                              "tgBot", "iconImg")
values (5499157826,
        'Fintopio',
        'New Payment Era',
        'en ru',
        'https://',
        'https://twitter.com/fintopio',
        'https://t.me/fintopionews',
        'https://t.me/fintopiochat',
        'https://t.me/fintopio',
        'https://ton.app/media/1e07db4e-4026-44cf-8419-3e1006a10180.png');
insert into public."Project" ("ownerTgId", "name", tagline, "langCodes", website, twitter, "tgChannel", "tgChat",
                              "tgBot", "iconImg")
values (5499157826,
        'Vertus',
        'Vertus is a new generation TON Wallet',
        'en',
        'https://',
        'https://twitter.com/the_vertus',
        'https://t.me/the_vertus',
        null,
        'https://t.me/Vertus_App_bot',
        'https://ton.app/media/c71e8a99-6ce0-4a07-87aa-0b4da461272a.jpg');
insert into public."Project" ("ownerTgId", "name", tagline, "langCodes", website, twitter, "tgChannel", "tgChat",
                              "tgBot", "iconImg")
values (5499157826,
        'Gem Wallet',
        'Web3 cryptocurrency wallet for everyone!',
        'en ja ru es zh',
        'https://gemwallet.com',
        null,
        null,
        null,
        null,
        'https://ton.app/media/1a55f884-8c22-4382-a472-9592d1d7aac7.png');
insert into public."Project" ("ownerTgId", "name", tagline, "langCodes", website, twitter, "tgChannel", "tgChat",
                              "tgBot", "iconImg")
values (5499157826,
        'SwapWallet',
        '🚀 Your key to seamless crypto transactions on Telegram!\n\n',
        'zh en fa ru fr',
        'https://',
        null,
        null,
        null,
        null,
        'https://ton.app/media/aa7f22b4-7ac5-4fff-869c-a5f5a64df95e.png');
insert into public."Project" ("ownerTgId", "name", tagline, "langCodes", website, twitter, "tgChannel", "tgChat",
                              "tgBot", "iconImg")
values (5499157826,
        'TONPAY',
        'A fast, convenient, and secure Telegram TON wallet.',
        'en',
        'https://t.me/tonpay_robot',
        null,
        'https://t.me/tonpay_official',
        null,
        'https://t.me/tonpay',
        'https://ton.app/media/4e673573-7583-497b-8150-4dbcceae39d4.png');
insert into public."Project" ("ownerTgId", "name", tagline, "langCodes", website, twitter, "tgChannel", "tgChat",
                              "tgBot", "iconImg")
values (5499157826,
        'BFinance',
        'BFinance - Issuing crypto card in Telegram',
        'en',
        'https://t.me/bfinancebot',
        null,
        'https://t.me/bfinancepay',
        null,
        'https://t.me/bfinancebot',
        'https://ton.app/media/0ffae3c1-002f-4743-bca0-e2f3da8ed5cd.jpg');
insert into public."Project" ("ownerTgId", "name", tagline, "langCodes", website, twitter, "tgChannel", "tgChat",
                              "tgBot", "iconImg")
values (5499157826,
        'Sender',
        'Your favorite Web3 wallet',
        'ru en',
        'https://senderwallet.io/',
        null,
        null,
        null,
        null,
        'https://ton.app/media/dd02a1bd-c333-4c0a-92d7-902d7067aa05.png');
insert into public."Project" ("ownerTgId", "name", tagline, "langCodes", website, twitter, "tgChannel", "tgChat",
                              "tgBot", "iconImg")
values (5499157826,
        'Atomic Wallet',
        'Atomic is a secure wallet for TON and dozens of other top assets. ',
        'nl en ru es de',
        'https://',
        'https://twitter.com/atomicwallet',
        'https://t.me/AtomicWalletNews',
        null,
        null,
        'https://ton.app/media/5655dde5-4241-4a9a-8a3b-8b4eebc4430c.png');
insert into public."Project" ("ownerTgId", "name", tagline, "langCodes", website, twitter, "tgChannel", "tgChat",
                              "tgBot", "iconImg")
values (5499157826,
        'Tonspay',
        'Tonspay is a crypto payment solution support for multichains . also supports MPC wallet .\n',
        'en',
        'https://',
        'https://twitter.com/tonsprotocols',
        'https://t.me/tonspays',
        'https://t.me/+5GkZeJOXluMxYWVl',
        'https://t.me/tonspay_bot',
        'https://ton.app/media/ec90e284-47af-4045-84bb-118798f4f405.png');
insert into public."Project" ("ownerTgId", "name", tagline, "langCodes", website, twitter, "tgChannel", "tgChat",
                              "tgBot", "iconImg")
values (5499157826,
        'Wallet Explorer',
        'Wallet & crypto exchange',
        null,
        'https://t.me/WalletExplorerBot',
        null,
        null,
        null,
        null,
        'https://ton.app/media/d9e19fc8-83b5-44df-b391-8f01e67bf2d8.jpg');
insert into public."Project" ("ownerTgId", "name", tagline, "langCodes", website, twitter, "tgChannel", "tgChat",
                              "tgBot", "iconImg")
values (5499157826,
        'Kolo Bot',
        '💳 Apply to the waiting list and get a worldwide Crypto Card by Mastercard.',
        'en',
        'https://',
        'https://twitter.com/KoloHub',
        'https://t.me/KoloAnn',
        'https://t.me/KoloTalks',
        'https://t.me/kolo',
        'https://ton.app/media/46ae9dc6-b9c3-471d-86ea-2db641b3e1f3.png');
insert into public."Project" ("ownerTgId", "name", tagline, "langCodes", website, twitter, "tgChannel", "tgChat",
                              "tgBot", "iconImg")
values (5499157826,
        'Matrix Wallet',
        'Self-custodial, multi-chain wallet on Telegram',
        'en',
        'https://',
        null,
        null,
        null,
        'https://t.me/MatrixWalletBot',
        'https://ton.app/media/98ae6fc3-5d10-4f35-9d9b-6a7f72136868.png');
insert into public."Project" ("ownerTgId", "name", tagline, "langCodes", website, twitter, "tgChannel", "tgChat",
                              "tgBot", "iconImg")
values (5499157826,
        'Defexa',
        'Web3 bank with non-custodial cards, decentralized chats, zero-fee DEX, upcoming airdrop, and TON.',
        'en es pt',
        'https://',
        'https://twitter.com/DefexaCrypto',
        'https://t.me/defexa',
        'https://t.me/defexawallet',
        null,
        'https://ton.app/media/958eb353-1911-407e-afef-4c19bbbc5797.png');
insert into public."Project" ("ownerTgId", "name", tagline, "langCodes", website, twitter, "tgChannel", "tgChat",
                              "tgBot", "iconImg")
values (5499157826,
        'XTON crypto wallet',
        'Crypto wallet for TON blockchain',
        null,
        'https://xtonwallet.com/',
        null,
        null,
        null,
        null,
        'https://ton.app/media/8737616e-9d4d-4088-8eb3-a52cc8c3094e.jpg');
insert into public."Project" ("ownerTgId", "name", tagline, "langCodes", website, twitter, "tgChannel", "tgChat",
                              "tgBot", "iconImg")
values (5499157826,
        'CryptoChill',
        'TON and other cryptocurrency payment processing with unlimited scaling',
        'en',
        'https://',
        'https://twitter.com/cryptochill',
        'https://t.me/CryptoChillGateway',
        null,
        null,
        'https://ton.app/media/c963fb0b-298b-4dd4-88f5-4d4f179b63a3.png');
insert into public."Project" ("ownerTgId", "name", tagline, "langCodes", website, twitter, "tgChannel", "tgChat",
                              "tgBot", "iconImg")
values (5499157826,
        'Tonspack',
        'The only multichain wallet your need in mobile crypto',
        'en',
        'https://',
        'https://x.com/tonspack',
        'https://t.me/tonspays',
        'https://t.me/Tonspackdev',
        'https://t.me/tonspack_bot/app',
        'https://ton.app/media/8d574927-b0d1-4efa-9979-8672ab8b791a.png');
insert into public."Project" ("ownerTgId", "name", tagline, "langCodes", website, twitter, "tgChannel", "tgChat",
                              "tgBot", "iconImg")
values (5499157826,
        'Scaleton',
        'Your DeFi-wallet with Jetton support',
        'en ru',
        'https://scaleton.co',
        null,
        null,
        null,
        null,
        'https://ton.app/media/fc2bce1e-fe42-40cf-acb0-74325041748b.jpg');
insert into public."Project" ("ownerTgId", "name", tagline, "langCodes", website, twitter, "tgChannel", "tgChat",
                              "tgBot", "iconImg")
values (5499157826,
        'OpenShield',
        'Conveniently interact with digital assets.',
        'ru',
        'https://',
        null,
        'https://t.me/ShieldFoundation',
        null,
        'https://t.me/OpenShieldBot',
        'https://ton.app/media/e089833b-701a-4837-a15b-c5289ac1462d.png');
insert into public."Project" ("ownerTgId", "name", tagline, "langCodes", website, twitter, "tgChannel", "tgChat",
                              "tgBot", "iconImg")
values (5499157826,
        'RoWallet ',
        'RoWallet: crypto wallet for TON and more directly in a Telegram bot!',
        'ru',
        'https://',
        null,
        'https://t.me/rowalletnew',
        null,
        'https://t.me/rowalletbot/app',
        'https://ton.app/media/17a1a1e3-bf8c-475f-b494-fef024779d5e.png');
insert into public."Project" ("ownerTgId", "name", tagline, "langCodes", website, twitter, "tgChannel", "tgChat",
                              "tgBot", "iconImg")
values (5499157826,
        'MathWallet',
        'Multichain Crypto Wallet for 4 million users, 200+ blockchains & http://mathdapp.store ',
        'en',
        'https://',
        'https://twitter.com/MathWallet',
        'https://t.me/mathwalletnews',
        'https://t.me/mathwallet',
        null,
        'https://ton.app/media/c64863b4-96c8-4675-ba67-6cdb189e8b43.png');

insert into public."Project" ("ownerTgId", "name", tagline, "langCodes", website, twitter, "tgChannel", "tgChat",
                              "tgBot", "iconImg")
values (5499157826,
        'Cwallet',
        'Securely Hold, Send, Receive, Exchange, Tip & Earn 800+ Cryptocurrencies With Cwallet.',
        'ar en hi ja fr',
        'https://cwallet.com/',
        'https://twitter.com/Cwalletofficial',
        'https://t.me/cctipnews',
        'https://t.me/cctip_svip',
        'https://t.me/cctip_bot',
        'https://ton.app/media/c90e9ecd-4a7a-4b8d-9870-dd43871b534f.jpg');
insert into public."Project" ("ownerTgId", "name", tagline, "langCodes", website, twitter, "tgChannel", "tgChat",
                              "tgBot", "iconImg")
values (5499157826,
        'Sendity',
        'Buy, sell and pay with our crypto card.',
        'en ru',
        'https://',
        'https://x.com/sendity_cc',
        'https://t.me/sendity',
        'https://t.me/sendity_chat',
        'https://t.me/sendity_bot',
        'https://ton.app/media/e653b3bd-e06c-4084-8e16-e82256656694.jpg');
insert into public."Project" ("ownerTgId", "name", tagline, "langCodes", website, twitter, "tgChannel", "tgChat",
                              "tgBot", "iconImg")
values (5499157826,
        'Ammer Wallet',
        'Secure mobile wallet for your crypto and NFTs',
        'en ru',
        'https://ammer.app',
        null,
        null,
        null,
        null,
        'https://ton.app/media/ff593c17-3d01-48dd-889d-df73f6611052.jpg');
